apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: node
    in-service: "true"
  name: node
  namespace: live
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node
        in-service: "true"
    spec:
      containers:
      - env:
        - name: SITE_CONCEPTS
          valueFrom:
            configMapKeyRef:
              name: ms-configs
              key: xt_site_concepts
              optional: true			  
        image: us.gcr.io/strong-land-247018/devops/nodeapp:latest
        imagePullPolicy: Always
        name: node
        ports:
        - containerPort: 3000
          name: node-port
          protocol: TCP
        resources:
          limits:
            cpu: "0.25"
            memory: 10m
          requests:
            cpu: "0.3"
            memory: 50m
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: my-gcr-account
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  ports:
  - name: node-port
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node
    in-service: "true"
  sessionAffinity: None
  type: LoadBalancer